### ISSUE TITLE
Google Idp signout returns 500 Internal Server Error

### ISSUE THREAD

**Issue by pawelros** [LykkeOSS/ironclad#138]
logs: `System.InvalidOperationException: Cannot redirect to the end session endpoint, the configuration may be missing or invalid.`

Google doesn't have an end session endpoint.
https://accounts.google.com/.well-known/openid-configuration

**Comment by cameronfletcher** [comment]
https://github.com/LykkeOSS/ironclad/blob/dev/src/Ironclad/Startup.cs#L143

**Comment by cameronfletcher** [comment]
This was fixed as a side effect of #146.
