### ISSUE TITLE
Move samples and test folders to root of repo

### ISSUE THREAD

**Issue by jchannon** [LykkeOSS/ironclad#25]
A while ago most OSS libs moved to a similar structure which was put down in black and white by David Fowler, ASP.NET Core architect. https://gist.github.com/davidfowl/ed7564297c61fe9ab814

Our tests and samples exist under a src folder and should be moved up IMO

**Comment by cameronfletcher** [comment]
I have restructured the project to a structure that I'm comfortable with.  

The only outstanding question I have is where do you think the `Ironclad.Tests.Sdk` project should live? It's currently built and published as a NuGet package but lives under the tests folder. Should I move it out into the `/src` folder?

**Comment by cameronfletcher** [comment]
The repo contains some files it shouldn't. I'll raise a PR to remove them.
