### ISSUE TITLE
Use static files

### ISSUE THREAD

**Issue by pawelros** [LykkeOSS/ironclad#51]
Ironclad UI behind reverse proxy does not load assets correctly.
See https://lykkecorp.tech/auth/

**Comment by cameronfletcher** [comment]
Related? https://stackoverflow.com/questions/46593999/how-to-host-a-asp-net-core-application-under-a-sub-folder

**Comment by cameronfletcher** [comment]
This has been addressed with the changes to support `X-Forwarded-PathBase` in #72
